#!/bin/bash
if [ $# -eq 0 ]
then

      echo "No arguments supplied in cmd prompt,Please provide arguments !"
fi
if [ $1 -gt $2 ] && [ $1 -gt $3 ]
     then
     echo " $1 is largest number"
          elif [ $2 -gt $1 ] && [ $2 -gt $3 ]
             then
      		echo "$2 is the largest number"
    	      else
      		echo "$3 is the largest number"
  fi   	  
