#!/bin/bash
for (( i = 1; i <= 8; i++ ))
do
 for (( j = 1; j <= 8; j++ ))
do
total=$(( $i + $j ))
quotnt=`expr $total/2`;
quotnt1=`expr $quotnt*2`
if [[ $quotnt1 -eq $total ]]
then
echo -e -n "\033[47m  " 
else
echo -e -n "\033[40m  "
fi
done
echo
done
echo -e "\033[0m"
